# Generated by Django 4.1.7 on 2023-03-01 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwordHash', models.CharField(max_length=512)),
                ('registerOtp', models.CharField(max_length=6, null=True)),
                ('salt', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=100)),
                ('paymentVerified', models.BooleanField(default=False)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('registerCounter', models.PositiveIntegerField(default=0)),
                ('emailVerified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
