# Generated by Django 4.1.7 on 2023-03-05 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("astra_home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sportImage", models.FileField(null=True, upload_to="SportsImages")),
                ("sportsName", models.CharField(max_length=50)),
                ("poolPrice", models.PositiveIntegerField()),
                ("maxPlayers", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=512)),
                (
                    "sportsType",
                    models.CharField(
                        choices=[("T", "Team Sports"), ("I", "Individual Sports")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCartModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cartAmount", models.PositiveBigIntegerField(default=0)),
                (
                    "userId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="astra_home.siteusermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                ("email", models.EmailField(default="", max_length=254)),
                ("phone", models.CharField(default="", max_length=10)),
                ("orderStatus", models.BooleanField(default=False)),
                ("createdOn", models.DateTimeField(auto_now_add=True)),
                (
                    "userCartId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="astra_home.usercartmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                ("amount", models.PositiveIntegerField(default=0)),
                (
                    "sport",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astra_home.sportsmodel",
                    ),
                ),
                (
                    "userCartId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astra_home.usercartmodel",
                    ),
                ),
            ],
        ),
    ]
