# Generated by Django 4.1.7 on 2023-03-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra_home', '0002_sportsmodel_usercartmodel_ordermodel_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsmodel',
            name='sportImage',
        ),
        migrations.AddField(
            model_name='sportsmodel',
            name='posterImage',
            field=models.ImageField(null=True, upload_to='PosterImages'),
        ),
    ]
