# Generated by Django 4.1.7 on 2023-03-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra_home', '0003_remove_sportsmodel_sportimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsmodel',
            name='posterImage',
        ),
        migrations.AddField(
            model_name='sportsmodel',
            name='imageName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
