# Generated by Django 4.1.7 on 2023-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra_home', '0004_remove_sportsmodel_posterimage_sportsmodel_imagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsmodel',
            name='imageName',
        ),
        migrations.AddField(
            model_name='sportsmodel',
            name='imageUrl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
