# Generated by Django 4.1.7 on 2023-03-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra_home', '0005_remove_sportsmodel_imagename_sportsmodel_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='teamName',
            field=models.CharField(default='x', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsmodel',
            name='regFee',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
