# Generated by Django 4.1.7 on 2023-03-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astra_home', '0008_alter_cartmodel_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='userCartId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='astra_home.usercartmodel'),
        ),
        migrations.AlterField(
            model_name='usercartmodel',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='astra_home.siteusermodel'),
        ),
    ]
